// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig():Promise<Record<string, any>>;

export function GetImportedURLs():Promise<Array<Record<string, any>>>;

export function GetStatus():Promise<Record<string, any>>;

export function ImportURL(arg1:string):Promise<Record<string, any>>;

export function QuitApp():Promise<void>;

export function SaveConfig(arg1:Record<string, any>):Promise<Record<string, any>>;

export function ToggleProxy():Promise<Record<string, any>>;
