// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetImportedURLs() {
  return window['go']['main']['App']['GetImportedURLs']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ImportURL(arg1) {
  return window['go']['main']['App']['ImportURL'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ToggleProxy() {
  return window['go']['main']['App']['ToggleProxy']();
}
